include: package:lint/analysis_options.yaml

linter:
  rules:
    sort_pub_dependencies: false

    import_of_legacy_library_into_null_safe: false

    omit_local_variable_types: true
    prefer_adjacent_string_concatenation: true
    prefer_single_quotes: true
    unawaited_futures: true

    prefer_relative_imports: true
    unnecessary_lambdas: true
    
    use_to_and_as_if_applicable: true
    one_member_abstracts : true
    prefer_mixin: true
    avoid_returning_null: true 
    avoid_returning_this: true 
    avoid_types_on_closure_parameters: true 
    avoid_equals_and_hash_code_on_mutable_classes: true 